version: '3'

services:

  mysql-dev:
    image: mysql:5.5
    container_name: mysqldev
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: dbpedia_metrics
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    volumes:
      - "./data:/var/lib/mysql"
      - "./data/dbpedia_metrics.sql:/docker-entrypoint-initdb.d/dbpedia_metrics.sql"
    ports:
      - "3308:3306"

  # message bus
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbit
    ports:
      - "8081:15672"
      # Forwarding the port for testing
      - "5672:5672"
